[package]
name = "spdx-expression"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "SPDX Expression"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"

[dev-dependencies]
pretty_assertions = "1"